<MyLayout>:
    BoxLayout:
        orientation: 'vertical'
        padding: "130dp"
        spacing: "20dp"
        size: root.width, root.height
        canvas.before:
            Rectangle:
                pos:self.pos
                size:self.size
                source: 'Bg.png'       
        FloatLayout:
            size: root.width, root.height
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            Image:
                source: "snake_2.png"
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                size_hint_x: None
                width: 200
                height: 200
                pos_hint: {"center_x": 0.5, "center_y" : 0.9}
            Label:
                text:'      LEADERBOARDS      '
                bold: 'yes'
                underline: 'yes'
                font_size: '30sp'
                color: 'white'
                halign: "center"
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.6}
                size_hint: (0.03,0.02)
            Label:
                text:' Here are the players who marked their way onto the game: \n'
                font_size: '20sp'
                color: 'white'
                halign: "center"
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                size_hint: (0.03,0.02)
            Label:
                text: 'Russel Adler \n'
                font_size: '18sp'
                color: 'white'
                halign: 'center'
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.4}
                size_hint: (0.03,0.02)
            Label:
                text: 'Score: 1000 points \n'
                font_size: '15sp'
                color: 'white'
                halign: 'center'
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.3}
                size_hint: (0.03,0.02)
            Label:
                text: 'Soap Mactavish \n'
                font_size: '18sp'
                color: 'white'
                halign: 'center'
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.2}
                size_hint: (0.03,0.02)
            Label:
                text: 'Score: 500 points \n'
                font_size: '15sp'
                color: 'white'
                halign: 'center'
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.1}
                size_hint: (0.03,0.02)

            Label:
                text:'Innovators: Gabrentina|| Manzano|| Quiambao|| Valle'
                font_size: '20sp'
                color: 'white'
                halign: "center"
                size_hint: None, None
                pos_hint: {'center_x': 0.5, 'center_y': 0}
                size_hint: (0.03,0.02)
            